export enum NatImplementor {
  MIN_OF_ENV = "Ministry of Environment and Climate Change",
  MIN_OF_STATE_ENERGY = "Ministry of State for Energy Affairs",
  MIN_OF_FINANCE = "Ministry of Finance",
  MIN_OF_MUNICIPALITY = "Ministry of Municipality",
  MIN_OF_TRANSPORT = "Ministry of Transport",
  MIN_OF_COMMERCE = "Ministry of Commerce and Industry",
  MIN_OF_HEALTH = "Ministry of Public Health",
  MIN_OF_EDUCATION = "Ministry of Education and Higher Education",
  MIN_OF_FOREIGN = "Ministry of Foreign Affairs",
  MIN_OF_INTERIOR = "Ministry of Interior",
  MIN_OF_DEFENCE = "Ministry of Defence Affairs",
  MIN_OF_LABOUR = "Ministry of Labour",
  MIN_OF_COMMS_TECH = "Ministry of Communications and Information Technology",
  MIN_OF_CABINET = "Ministry of State for Cabinet Affairs",
  MIN_OF_SOCIAL_DEV = "Ministry of Social Development and Family",
  MIN_OF_CULTURE = "Ministry of Culture",
  MIN_OF_LABOUR_SOCIAL = "Ministry of Labour and Social Affairs",
  MIN_OF_PLANNING_STATS = "Ministry of Development Planning & Statistics",
  STATE_AUDIT_BUREAU = "State Audit Bureau",
  QATAR_ENERGY = "QatarEnergy",
  QATAR_ELEC_WATER = "Qatar General Electricity & Water Corporation",
  PUBLIC_WORKS_AUTH = "Public Works Authority (Ashghal)",
  QATAR_PORTS = "Qatar Ports Management Company",
  QATAR_CAA = "Qatar Civil Aviation Authority",
  MOWASALAT = "Mowasalat (Karwa)",
  QATAR_MET_DEPT = "Qatar Meteorology Department",
  QATAR_AIRWAYS = "Qatar Airways",
  QATAR_INVEST_AUTH = "Qatar Investment Authority",
  QATAR_DEV_FUND = "Qatar Fund for Development",
  QEERI = "Qatar Environment & Energy Research Institute",
}

export enum IntImplementor {
  AFC = "AFC",
  AFD = "AFD",
  AFDB = "AFDB",
  EBRD = "EBRD",
  EIB = "EIB",
  FAO = "FAO",
  GCF = "GCF",
  GEF = "GEF",
  GIZ = "GIZ",
  IMF = "IMF",
  IMO = "IMO",
  IUCN = "IUCN",
  NEFCO = "NEFCO",
  UNWO = "UN Women",
  UNDP = "UNDP",
  UNEP = "UNEP",
  UNESCO = "UNESCO",
  UNFCCC = "UNFCCC",
  UNFPA = "UNFPA",
  UNICEF = "UNICEF",
  UNIDO = "UNIDO",
  USAID = "USAID",
  WFP = "WFP",
  WMO = "WMO",
  WB = "World Bank",
}

export enum Recipient {
  MIN_OF_ENV = "Ministry of Environment and Climate Change",
  MIN_OF_STATE_ENERGY = "Ministry of State for Energy Affairs",
  MIN_OF_FINANCE = "Ministry of Finance",
  MIN_OF_MUNICIPALITY = "Ministry of Municipality",
  MIN_OF_TRANSPORT = "Ministry of Transport",
  MIN_OF_COMMERCE = "Ministry of Commerce and Industry",
  MIN_OF_HEALTH = "Ministry of Public Health",
  MIN_OF_EDUCATION = "Ministry of Education and Higher Education",
  MIN_OF_FOREIGN = "Ministry of Foreign Affairs",
  MIN_OF_INTERIOR = "Ministry of Interior",
  MIN_OF_DEFENCE = "Ministry of Defence Affairs",
  MIN_OF_LABOUR = "Ministry of Labour",
  MIN_OF_COMMS_TECH = "Ministry of Communications and Information Technology",
  MIN_OF_CABINET = "Ministry of State for Cabinet Affairs",
  MIN_OF_SOCIAL_DEV = "Ministry of Social Development and Family",
  MIN_OF_CULTURE = "Ministry of Culture",
  MIN_OF_LABOUR_SOCIAL = "Ministry of Labour and Social Affairs",
  MIN_OF_PLANNING_STATS = "Ministry of Development Planning & Statistics",
  STATE_AUDIT_BUREAU = "State Audit Bureau",
  QATAR_ENERGY = "QatarEnergy",
  QATAR_ELEC_WATER = "Qatar General Electricity & Water Corporation",
  PUBLIC_WORKS_AUTH = "Public Works Authority (Ashghal)",
  QATAR_PORTS = "Qatar Ports Management Company",
  QATAR_CAA = "Qatar Civil Aviation Authority",
  MOWASALAT = "Mowasalat (Karwa)",
  QATAR_MET_DEPT = "Qatar Meteorology Department",
  QATAR_AIRWAYS = "Qatar Airways",
  QATAR_INVEST_AUTH = "Qatar Investment Authority",
  QATAR_DEV_FUND = "Qatar Fund for Development",
  QEERI = "Qatar Environment & Energy Research Institute",
}

export enum EntityType {
  ACTION = "action",
  PROGRAMME = "programme",
  PROJECT = "project",
  ACTIVITY = "activity",
  SUPPORT = "support",
}

export enum LogEventType {
  ACTION_CREATED = 0,
  KPI_ADDED = 1,
  KPI_UPDATED = 2,
  PROGRAMME_LINKED = 3,
  ACTION_UPDATED = 4,
  PROGRAMME_CREATED = 5,
  LINKED_TO_ACTION = 6,
  UNLINKED_FROM_ACTION = 7,
  PROJECT_CREATED = 8,
  PROJECT_LINKED = 9,
  LINKED_TO_PROGRAMME = 10,
  UNLINKED_FROM_PROGRAMME = 11,
  ACTIVITY_CREATED = 12,
  ACTIVITY_LINKED = 13,
  LINKED_TO_PROJECT = 14,
  UNLINKED_FROM_PROJECT = 15,
  PROGRAMME_UPDATED = 16,
  PROJECT_UPDATED = 17,
  ACTION_VERIFIED = 18,
  PROJECT_VERIFIED = 19,
  ACTIVITY_UPDATED = 20,
  ACTIVITY_VERIFIED = 21,
  SUPPORT_CREATED = 22,
  SUPPORT_LINKED = 23,
  LINKED_TO_ACTIVITY = 24,
  SUPPORT_VERIFIED = 25,
  SUPPORT_UPDATED = 26,
  UNLINKED_FROM_ACTIVITY = 27,
  PROGRAMME_VERIFIED = 28,
  MTG_UPDATED = 29,
  ACTION_UNVERIFIED = 30,
  PROGRAMME_UNVERIFIED = 31,
  PROJECT_UNVERIFIED = 32,
  ACTIVITY_UNVERIFIED = 33,
  SUPPORT_UNVERIFIED = 34,
  // unverified due to an update in one of the attached entities
  ACTION_UNVERIFIED_DUE_LINKED_ENTITY_UPDATE = 35,
  PROGRAMME_UNVERIFIED_DUE_LINKED_ENTITY_UPDATE = 36,
  PROJECT_UNVERIFIED_DUE_LINKED_ENTITY_UPDATE = 37,
  ACTIVITY_UNVERIFIED_DUE_LINKED_ENTITY_UPDATE = 38,
  SUPPORT_UNVERIFIED_DUE_LINKED_ENTITY_UPDATE = 39,
  // unverified due to the entity being updated
  ACTION_UNVERIFIED_DUE_UPDATE = 40,
  PROGRAMME_UNVERIFIED_DUE_UPDATE = 41,
  PROJECT_UNVERIFIED_DUE_UPDATE = 42,
  ACTIVITY_UNVERIFIED_DUE_UPDATE = 43,
  SUPPORT_UNVERIFIED_DUE_UPDATE = 44,
  // unverified due to new attachment or detachment in the tree
  ACTION_UNVERIFIED_DUE_ATTACHMENT_CHANGE = 45,
  PROGRAMME_UNVERIFIED_DUE_ATTACHMENT_CHANGE = 46,
  PROJECT_UNVERIFIED_DUE_ATTACHMENT_CHANGE = 47,
  ACTIVITY_UNVERIFIED_DUE_ATTACHMENT_CHANGE = 48,
  SUPPORT_UNVERIFIED_DUE_ATTACHMENT_CHANGE = 49,

  // unverified due to an attachment being deleted from the tree
  ACTION_UNVERIFIED_DUE_ATTACHMENT_DELETE = 50,
  PROGRAMME_UNVERIFIED_DUE_ATTACHMENT_DELETE = 51,
  PROJECT_UNVERIFIED_DUE_ATTACHMENT_DELETE = 52,
  ACTIVITY_UNVERIFIED_DUE_ATTACHMENT_DELETE = 53,

  //activity unverified due to mitigation timeline update
  ACTIVITY_UNVERIFIED_DUE_MITIGATION_TIMELINE_UPDATE = 54,
}

export enum GHGS {
  CO = "CO2",
  CH = "CH4",
  NO = "N2O",
  HFC = "HFCs",
  NF = "NF3",
  PFC = "PFCs",
  SF = "SF6",
}

export enum SubSector {
  GRID_GENERAT = "Grid-Connected Generation (electricity)",
  OFF_GRID_GENERAT = "Off-Grid / Rural Generation (electricity)",
  TRANS_DISTR = "Transmission & Distribution (electricity)",
  FUEL = "Fuels",
  GOV = "Government",
  INDUSTRY = "Industry",
  APPLIANCES = "Appliances",
  WATER = "Water",
  CITIES = "Cities",
  BUILDINGS = "Buildings",
  LAND_TRANSPORT = "Land (transport)",
  MARITIME_TRANSPORT = "Maritime (transport)",
  AVIATION_TRANSPORT = "Aviation (transport)",
  WASTE_WATER = "Wastewater",
  WASTE_SOLID = "Solid Waste",
  FORESTRY = "Forestry",
  AGR_FORESTRY = "Agroforestry",
  AGRICULTURE = "Agriculture",
  LAND_USE = "Land Use",
  COASTAL = "Coastal",
  FISHING = "Fishing",
  BIO_DIVERSITY = "Biodiversity",
  ECO_SYS = "Ecosystems",
  NATURE_BASED = "Nature Based Solutions",
  TOURISM = "Tourism",
  COMMERCIAL = "Commercial",
  HOUSE_HOLDS = "Households",
  FOOD_SYSTEMS = "Food systems",
  MULTI_SUB_SEC = "Multi-Subsector",
  NA = "Not Applicable",
}

export enum IpccSubSector {
  "1A1" = "1A1 Energy Industries",
  "1A2" = "1A2 Manufacturing Industries and Construction",
  "1A3a" = "1A3a Civil Aviation",
  "1A3b" = "1A3b Road Transportation",
  "1A3c" = "1A3c Railways",
  "1A3d" = "1A3d Water-borne Navigation",
  "1A3e" = "1A3e Other Transportation",
  "1A4" = "1A4 Other Sectors",
  "1A5" = "1A5 Non-Specified",
  "1B1" = "1B1 Solid Fuels",
  "1B2" = "1B2 Oil and Natural Gas",
  "1B3" = "1B3 Other Emissions from Energy Production",
  "1C1" = "1C1 Transport of CO2",
  "1C2" = "1C2 Injections and Storage",
  "1C3" = "1C3 Other",
  "2A" = "2A Mineral Industry",
  "2B" = "2B Chemical Industry",
  "2C" = "2C Metal Industry",
  "2D" = "2D Non-Energy Products from Fuels and Solvent Use",
  "2E" = "2E Electronics Industry",
  "2F" = "2F Product Uses as Substitutes for Ozone Depleting Substances",
  "2G" = "2G Other Product Manufacture and Use",
  "2H" = "2H Other",
  "3A1" = "3A1 Enteric Fermentation",
  "3A2" = "3A2 Manure Management",
  "3B1" = "3B1 Forest Land",
  "3B2" = "3B2 Cropland",
  "3B3" = "3B3 Grassland",
  "3B4" = "3B4 Wetlands",
  "3B5" = "3B5 Settlements",
  "3B6" = "3B6 Other Land",
  "3C" = "3C Aggregate Sources and Non-CO2 Emissions Sources on Land",
  "3D" = "3D Other",
  "4A" = "4A Solid Waste Disposal",
  "4B" = "4B Biological Treatment of Solid Waste",
  "4C" = "4C Incineration and Open Burning of Waste",
  "4D" = "4D Wastewater Treatment and Discharge",
  "4E" = "4E Other",
  "5A" = "5A Indirect N2O Emissions from the Atmospheric Deposition of Nitrogen in Nox and NH3",
  "5B" = "5B Other",
}

export enum ExportFileType {
  XLSX = "xlsx",
  CSV = "csv",
}

export enum KPIAction {
  NONE = "None",
  CREATED = "Created",
  UPDATED = "Updated",
}

export enum Annexes {
  TWO = "2",
  THREE = "3",
}

export enum Reports {
  FIVE = "5",
  SIX = "6",
  SEVEN = "7",
  EIGHT = "8",
  NINE = "9",
  TEN = "10",
  ELEVEN = "11",
  TWELVE = "12",
  THIRTEEN = "13",
}

export enum Method {
  CREATE = "create",
  UPDATE = "update",
  VIEW = "view",
}

export enum SystemResourceCategory {
  GHG = "GHG",
  FAQ = "FAQ",
}

export enum SystemResourceType {
  DOCUMENT = "DOCUMENT",
}
