service: lambda-layer-mrv

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  iam:
    role: arn:aws:iam::302213478610:role/lambda-role-dev
  vpc:
    subnetIds:
      - subnet-042cb038d752b50dd
      - subnet-0646392cded0ed2f7
    securityGroupIds:
      - sg-03937a2ebf99900ca

layers:
  service-dependencies-mrv-1:
    path: dependency_layer
    name: service-dependencies-mrv-${self:provider.stage}-1
    description: "Node Modules Dependencies 1"
    package:
      exclude:
        - node_modules/**
        - '!node_modules/@*/**'
        - '!node_modules/a*/**'
        - '!node_modules/b*/**'
        - '!node_modules/c*/**'
  service-dependencies-mrv-2:
    path: dependency_layer
    name: service-dependencies-mrv-${self:provider.stage}-2
    description: "Node Modules Dependencies 2"
    package:
      exclude:
        - 'node_modules/@*/**'
        - 'node_modules/a*/**'
        - 'node_modules/b*/**'
        - 'node_modules/c*/**'
        - 'node_modules/typescript/**'