name: Carbon Transparency Test Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - "staging"
    paths:
      - backend/**
      - web/**
      - .github/workflows/deployment*

env:
  REGISTRY: ${{ secrets.ACR_USERNAME }}.azurecr.io

jobs:
  changes:
    name: Carbon Transparency Deploy Pre Check
    runs-on: ubuntu-latest
    outputs:
      backend-changes: ${{ steps.changes.outputs.backend-changes }}
      workflows-changes: ${{ steps.changes.outputs.workflows-changes }}
      frontend-changes: ${{ steps.changes.outputs.frontend-changes }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Determine changed services
        id: changes
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)

          if echo "$CHANGED_FILES" | grep -q "backend/"; then
            echo "Backend changes detected."
            echo "backend-changes=true" >> $GITHUB_OUTPUT
          else
            echo "No Backend changes detected."
            echo "backend-changes=false" >> $GITHUB_OUTPUT
          fi

          if echo echo "$CHANGED_FILES" | grep -q ".github/workflows/"; then
            echo "Workflow changes detected."
            echo "workflows-changes=true" >> $GITHUB_OUTPUT
          else
            echo "No Workflow changes detected."
            echo "workflows-changes=false" >> $GITHUB_OUTPUT
          fi

          if echo "$CHANGED_FILES" | grep -q "web/"; then
            echo "Frontend changes detected."
            echo "frontend-changes=true" >> $GITHUB_OUTPUT
          else
            echo "No Frontend changes detected."
            echo "frontend-changes=false" >> $GITHUB_OUTPUT
          fi

  backend-build:
    needs: changes
    if: needs.changes.outputs.backend-changes == 'true' || needs.changes.outputs.workflows-changes == 'true'
    name: Carbon Transparency Backend Build
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-'backend'
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_USERNAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build, tag, and push the backend images to ACR
        id: build-backend-image
        env:
          REGISTRY: ${{ env.REGISTRY }}
          REPOSITORY: transparency-services
          IMAGE_TAG: ${{ github.head_ref || github.ref_name }}
        run: |
          # Build a docker container and push it to ACR 
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f backend/services/Dockerfile .
          echo "Pushing image to ACR..."
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$REGISTRY/$REPOSITORY:$IMAGE_TAG"

  frontend-build:
    needs: changes
    if: needs.changes.outputs.frontend-changes == 'true' || needs.changes.outputs.workflows-changes == 'true' 
    name: Carbon Transparency Frontend Build
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-'web'
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_USERNAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build, tag, and push the frontend images to ACR
        id: build-frontend-image
        env:
          REGISTRY: ${{ env.REGISTRY }}
          REPOSITORY: transparency-web
          IMAGE_TAG: ${{ github.head_ref || github.ref_name }}
        run: |
          # Build a docker container and push it to ACR 
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f web/Dockerfile . --build-arg PORT=3030 --build-arg REACT_APP_BACKEND=http://localhost:9000 --build-arg REACT_APP_STAT_URL=http://localhost:9100 --build-arg COUNTRY_NAME="CountryX" --build-arg COUNTRY_FLAG_URL="https://transparency-test.carbreg.org:9000/flag.png" --build-arg COUNTRY_CODE="NG" --build-arg REACT_APP_MAP_TYPE="Mapbox" --build-arg REACT_APP_GOVERNMENT_MINISTRY:"Ministry Of Environment" --build-arg REACT_APP_MAPBOXGL_ACCESS_TOKEN=${{ secrets.MAPBOXGL_ACCESS_TOKEN }} 
          echo "Pushing image to ACR..."
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$REGISTRY/$REPOSITORY:$IMAGE_TAG"

  backend-deploy:
    needs: backend-build
    name: Carbon Transparency Backend Deploy
    runs-on: [self-hosted, mrv-test]
    concurrency:
      group: mrv-test-deploy
      cancel-in-progress: false
    steps:
      - name: Deploy backend on the Azure VM
        run: sudo /home/azureuser/repos/carbon-transparency/mrv_backend_deploy.sh

  frontend-deploy:
    needs: frontend-build
    name: Carbon Transparency Frontend Deploy
    runs-on: [self-hosted, mrv-test]
    concurrency:
      group: mrv-test-deploy
      cancel-in-progress: false
    steps:
      - name: Deploy frontend on the Azure VM
        run: sudo /home/azureuser/repos/carbon-transparency/mrv_frontend_deploy.sh
