upstream national_api {
    server national:3000;
}

upstream stats_api {
    server stats:3100;
}

server {
  listen 443 ssl;
  server_name transparency-demo.carbreg.org www.transparency-demo.carbreg.org;
  ssl_certificate /ssl_cert/fullchain.pem;
  ssl_certificate_key /ssl_cert/privkey.pem;
  root /usr/share/nginx/html/;

  location /national/ {
    proxy_pass http://national_api;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /stats/ {
    proxy_pass http://stats_api;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location / {
    root /usr/share/nginx/html/;
    include /etc/nginx/mime.types;
    try_files $uri $uri/ /index.html;
  }
}

server {
    listen 80 default_server;
    server_name _;
    return 301 https://$host$request_uri;
}
